-- MySQL Script generated by MySQL Workbench
-- 11/17/16 15:58:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema boardsense
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boardsense
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boardsense` ;
USE `boardsense` ;

-- -----------------------------------------------------
-- Table `boardsense`.`Mountain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`Mountain` (
  `mountainName` VARCHAR(50) NOT NULL,
  `location` VARCHAR(50) NULL,
  `imageFilePath` VARCHAR(100) NULL,
  `peakAltitude` INT UNSIGNED NULL,
  PRIMARY KEY (`mountainName`),
  UNIQUE INDEX `mountainName_UNIQUE` (`mountainName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardsense`.`Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`Competition` (
  `competitionName` VARCHAR(50) NOT NULL,
  `competitionYear` INT UNSIGNED NOT NULL,
  `tier` VARCHAR(20) NULL,
  `mountainName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`competitionName`, `competitionYear`),
  INDEX `mountainName_idx` (`mountainName` ASC),
  CONSTRAINT `mountain`
    FOREIGN KEY (`mountainName`)
    REFERENCES `boardsense`.`Mountain` (`mountainName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardsense`.`BoardUsed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`BoardUsed` (
  `brand` VARCHAR(20) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `yearMade` INT UNSIGNED NOT NULL,
  `length` INT UNSIGNED NULL,
  `profile` VARCHAR(30) NULL,
  `price` DECIMAL(8,2) UNSIGNED NULL,
  `adLink` VARCHAR(50) NULL,
  PRIMARY KEY (`brand`, `model`, `yearMade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardsense`.`Snowboarder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`Snowboarder` (
  `snowboarderID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `height` INT UNSIGNED NULL,
  `ridingStyle` VARCHAR(10) NULL,
  PRIMARY KEY (`snowboarderID`),
  UNIQUE INDEX `snowboarderID_UNIQUE` (`snowboarderID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardsense`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`Category` (
  `categoryName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`categoryName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardsense`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`Participation` (
  `participationID` INT NOT NULL AUTO_INCREMENT,
  `result` INT UNSIGNED NULL,
  `competitionName` VARCHAR(50) NOT NULL,
  `competitionYear` INT UNSIGNED NOT NULL,
  `categoryName` VARCHAR(30) NULL,
  `snowboarderID` INT NULL,
  `brand` VARCHAR(20) NULL,
  `model` VARCHAR(45) NULL,
  `yearMade` INT UNSIGNED NULL,
  PRIMARY KEY (`participationID`),
  UNIQUE INDEX `participationID_UNIQUE` (`participationID` ASC),
  INDEX `competition_idx` (`competitionName` ASC, `competitionYear` ASC),
  INDEX `boardused_idx` (`brand` ASC, `model` ASC, `yearMade` ASC),
  INDEX `snowboarder_idx` (`snowboarderID` ASC),
  INDEX `category_idx` (`categoryName` ASC),
  UNIQUE INDEX `snowboarderID_UNIQUE` (`snowboarderID` ASC),
  CONSTRAINT `competition`
    FOREIGN KEY (`competitionName` , `competitionYear`)
    REFERENCES `boardsense`.`Competition` (`competitionName` , `competitionYear`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `boardused`
    FOREIGN KEY (`brand` , `model` , `yearMade`)
    REFERENCES `boardsense`.`BoardUsed` (`brand` , `model` , `yearMade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `snowboarder`
    FOREIGN KEY (`snowboarderID`)
    REFERENCES `boardsense`.`Snowboarder` (`snowboarderID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `category`
    FOREIGN KEY (`categoryName`)
    REFERENCES `boardsense`.`Category` (`categoryName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardsense`.`Trick`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`Trick` (
  `trickID` INT NOT NULL AUTO_INCREMENT,
  `boardGrabs` VARCHAR(45) NULL,
  `spinDegrees` INT UNSIGNED NULL,
  `trickName` VARCHAR(60) NULL,
  PRIMARY KEY (`trickID`),
  UNIQUE INDEX `trickID_UNIQUE` (`trickID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardsense`.`Performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boardsense`.`Performance` (
  `trickNo` INT UNSIGNED NULL,
  `trickID` INT NOT NULL,
  `participationID` INT NOT NULL,
  INDEX `participation_idx` (`participationID` ASC),
  INDEX `trick_idx` (`trickID` ASC),
  UNIQUE INDEX `participationID_UNIQUE` (`participationID` ASC),
  UNIQUE INDEX `trickID_UNIQUE` (`trickID` ASC),
  CONSTRAINT `participation`
    FOREIGN KEY (`participationID`)
    REFERENCES `boardsense`.`Participation` (`participationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trick`
    FOREIGN KEY (`trickID`)
    REFERENCES `boardsense`.`Trick` (`trickID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

DESCRIBE `BoardUsed`;
DESCRIBE `Category`;
DESCRIBE `Competition`;
DESCRIBE `Mountain`;
DESCRIBE `Participation`;
DESCRIBE `Performance`;
DESCRIBE `Snowboarder`;
DESCRIBE `Trick`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
